"""initial migration

Revision ID: 0cbc45f23d2a
Revises:
Create Date: 2025-09-05 08:54:13.164381

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0cbc45f23d2a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
